# Generated by Django 3.0.6 on 2020-05-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mobile')),
                ('des', models.TextField(verbose_name='Query')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacted ContactedDetailsDetails',
                'verbose_name_plural': 'Contacted Details',
                'ordering': ['-id'],
            },
        ),
    ]
