# Generated by Django 3.0.6 on 2020-05-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=200, verbose_name='Company Email ID')),
                ('logo', models.ImageField(blank=True, upload_to='gallery/images/%y%m%d', verbose_name='Company LOGO')),
                ('fb_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='FB URL')),
                ('tw_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='TWITTER URL')),
                ('rss_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='RSS FEED')),
                ('gp_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Google PLUS URL')),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Header Configurations',
                'verbose_name_plural': 'Header Configurations',
                'ordering': ['-id'],
            },
        ),
    ]
