# Generated by Django 3.0.6 on 2020-05-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_who_we_are'),
    ]

    operations = [
        migrations.AddField(
            model_name='who_we_are',
            name='style_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Style Name'),
        ),
        migrations.AddField(
            model_name='why_choose_us',
            name='style_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Style Name'),
        ),
        migrations.AlterField(
            model_name='who_we_are',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Titles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='why_choose_us',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Titles'),
            preserve_default=False,
        ),
    ]
