# Generated by Django 3.0.6 on 2020-05-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200530_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Why_Choose_Us',
            new_name='WhyChooseUs',
        ),
    ]
