# Generated by Django 3.0.6 on 2020-05-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200530_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Who_we_are',
            new_name='Whoweare',
        ),
    ]
