# Generated by Django 3.0.6 on 2020-05-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_why_choose_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Why_Choose_Us',
            new_name='WhyChooseUs',
        ),
    ]
